server:
  port: 8010
  max-http-header-size: 1048576
  tomcat:
    max-http-post-size: 1048576
spring:
  application:
    name: archives-common
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/document?useSSL=false
    username: root
    password: sheng
mybatis-plus:
  mapper-locations: classpath:com/lizi123/archives/mapper/*Mapper.xml
  type-aliases-package: com.lizi123.archives.domain,com.lizi123.archives.query
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true
#设置日志级别
logging:
  level:
    root: debug
#    com.xxx: debug