server:
  port: 8001
spring:
  application:
    name: archives-plat
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/document?useSSL=false
    username: root
    password: sheng
mybatis:
  config-location: classpath:com/lizi123/archives/mapper/*Mapper.xml
eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.236:7001/eureka
  instance:
    prefer-ip-address: true