server:
  port: 8002
spring:
  application:
    name: archives-product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/document
    username: root
    password: root
mybatis-plus:
  mapper-locations: classpath:com/lizi123/archives/mapper/*Mapper.xml
  type-aliases-package: com.lizi123.archives.domain,com.lizi123.archives.query
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true